# Generates every test fixture. The output is committed alongside this script and
# `test-fixtures.jl` asserts the two stay in step, so regenerate rather than
# hand-editing a fixture.
#
#     julia --project=test test/fixtures/make_fixtures.jl
#
# The files are synthetic and only a few days long: small enough to read by eye,
# and every edge case is deliberate rather than hoped for.

using Dates
using Printf

const HERE = @__DIR__

# ---------------------------------------------------------------------------
# Solar geometry. Used only to build physically consistent irradiance for the
# closure fixtures. The package itself must never gain a solar position
# dependency, so this lives in the test scaffolding.
# ---------------------------------------------------------------------------

"""NOAA low-precision solar position. Returns cos(zenith) at a UTC instant."""
function cos_zenith(lat_deg, lon_deg, t::DateTime)
    doy = Dates.dayofyear(t)
    hour = Dates.hour(t) + Dates.minute(t) / 60 + Dates.second(t) / 3600
    γ = 2π / 365 * (doy - 1 + (hour - 12) / 24)
    eqtime =
        229.18 *
        (0.000075 + 0.001868cos(γ) - 0.032077sin(γ) - 0.014615cos(2γ) - 0.040849sin(2γ))
    decl = (
        0.006918 - 0.399912cos(γ) + 0.070257sin(γ) - 0.006758cos(2γ) + 0.000907sin(2γ) -
        0.002697cos(3γ) + 0.00148sin(3γ)
    )
    time_offset = eqtime + 4 * lon_deg
    tst = hour * 60 + time_offset
    ha = deg2rad(tst / 4 - 180)
    φ = deg2rad(lat_deg)
    return sin(φ) * sin(decl) + cos(φ) * cos(decl) * cos(ha)
end

# ---------------------------------------------------------------------------
# EPW writing
# ---------------------------------------------------------------------------

const EPW_LAT = 52.1
const EPW_LON = 5.18
const EPW_ALT = 2.0

function epw_header(; tz_hours, records_per_hour, start_date, end_date, station = "De Bilt")
    return [
        @sprintf(
            "LOCATION,%s,-,NLD,TMYx,062600,%.2f,%.2f,%.1f,%.1f",
            station,
            EPW_LAT,
            EPW_LON,
            tz_hours,
            EPW_ALT
        ),
        "DESIGN CONDITIONS,0",
        "TYPICAL/EXTREME PERIODS,0",
        "GROUND TEMPERATURES,1,0.5,,,,10.1,10.2,10.3,10.4,10.5,10.6,10.7,10.8,10.9,11.0,11.1,11.2",
        "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
        "COMMENTS 1,Synthetic fixture generated by make_fixtures.jl",
        "COMMENTS 2,Not real observations. Do not use for modelling.",
        @sprintf(
            "DATA PERIODS,1,%d,Data,Sunday,%d/%d,%d/%d",
            records_per_hour,
            month(start_date),
            day(start_date),
            month(end_date),
            day(end_date)
        ),
    ]
end

"""
Encode a LOCAL end-of-interval timestamp as EPW `(date, hour, minute)`.

EPW hour `h` runs 1..24 and covers local `(h-1):00` to `h:00`. The minute field
runs 1..60 within that hour, so 60 means the end of it. Counting minutes from
midnight makes both the hour-24 rollover and sub-hourly records fall out of one
rule: `h = cld(M, 60)`, `m = M - 60(h - 1)`.

    01:00 -> h=1,  m=60      (hourly)
    01:15 -> h=2,  m=15      (15-minute)
    00:00 -> h=24, m=60 on the previous day
"""
function epw_datetime_fields(stamp::DateTime)
    m_from_midnight = hour(stamp) * 60 + minute(stamp)
    d = stamp
    if m_from_midnight == 0
        m_from_midnight = 1440
        d = stamp - Day(1)
    end
    h = cld(m_from_midnight, 60)
    return (d, h, m_from_midnight - 60 * (h - 1))
end

"""One EPW data row from a LOCAL end-of-interval timestamp."""
function epw_row(stamp::DateTime; ghi, dni, dhi, tdry, rh, pres, wdir, wspd, pwat, alb)
    d, h, minute_field = epw_datetime_fields(stamp)
    fields = [
        string(year(d)),
        string(month(d)),
        string(day(d)),
        string(h),
        string(minute_field),
        "?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9?9?9?9",
        @sprintf("%.1f", tdry),      # 7  dry bulb °C
        @sprintf("%.1f", tdry - 4),  # 8  dew point °C
        @sprintf("%.0f", rh),        # 9  relative humidity %
        @sprintf("%.0f", pres),      # 10 station pressure Pa
        "0",
        "0",                    # 11-12 extraterrestrial
        "350",                       # 13 horizontal IR
        @sprintf("%.0f", ghi),       # 14 global horizontal Wh/m2
        @sprintf("%.0f", dni),       # 15 direct normal Wh/m2
        @sprintf("%.0f", dhi),       # 16 diffuse horizontal Wh/m2
        "0",
        "0",
        "0",
        "0",          # 17-20 illuminance, luminance
        @sprintf("%.0f", wdir),      # 21 wind direction deg
        @sprintf("%.1f", wspd),      # 22 wind speed m/s
        "5",
        "5",                    # 23-24 sky cover
        "20.0",
        "77777",             # 25-26 visibility, ceiling
        "9",
        "999999999",            # 27-28 present weather
        @sprintf("%.0f", pwat),      # 29 precipitable water mm
        "0.080",                     # 30 aerosol optical depth
        "0",                         # 31 snow depth
        "88",                        # 32 days since snowfall
        @sprintf("%.3f", alb),       # 33 albedo
        "0.0",
        "0.0",                # 34-35 liquid precipitation
    ]
    return join(fields, ",")
end

"""
Build the local end-of-interval stamps for `ndays` starting at `start`, at
`records_per_hour`. Optionally drop or duplicate stamps to make a broken file.
"""
function local_stamps(start::Date, ndays::Int, records_per_hour::Int)
    step = Minute(60 ÷ records_per_hour)
    first_stamp = DateTime(start) + step
    last_stamp = DateTime(start) + Day(ndays)
    return collect(first_stamp:step:last_stamp)
end

"""
Physically consistent irradiance at a local stamp, given the UTC offset. Returns
`(ghi, dni, dhi, cosz)` in W/m² satisfying GHI = DHI + DNI*cos(z) exactly.
"""
function clear_sky(stamp_local::DateTime, tz_hours::Real)
    utc = stamp_local - Minute(round(Int, tz_hours * 60))
    μ = cos_zenith(EPW_LAT, EPW_LON, utc)
    if μ <= 0.01
        return (0.0, 0.0, 0.0, max(μ, 0.0))
    end
    dni = 900 * exp(-0.15 / μ)
    dhi = 80 * μ^0.5
    return (dhi + dni * μ, dni, dhi, μ)
end

function write_epw(dir, name, stamps, tz_hours, records_per_hour; corrupt = nothing)
    isempty(stamps) && error("no stamps for $name")
    header = epw_header(;
        tz_hours,
        records_per_hour,
        start_date = Date(first(stamps)),
        end_date = Date(last(stamps)),
    )
    rows = String[]
    for (i, s) in enumerate(stamps)
        ghi, dni, dhi, μ = clear_sky(s, tz_hours)
        if corrupt !== nothing
            ghi, dni, dhi = corrupt(i, ghi, dni, dhi, μ)
        end
        # EPW irradiance is Wh/m2 accumulated over the record.
        scale = 1 / records_per_hour
        push!(
            rows,
            epw_row(
                s;
                ghi = ghi * scale,
                dni = dni * scale,
                dhi = dhi * scale,
                tdry = 12 + 9μ,
                rh = 70 - 20μ,
                pres = 101_325,
                wdir = 230,
                wspd = 3.4 + μ,
                pwat = 15,
                alb = 0.2,
            ),
        )
    end
    path = joinpath(dir, name)
    open(path, "w") do io
        for line in header
            println(io, line)
        end
        for line in rows
            println(io, line)
        end
    end
    return path
end

# ---------------------------------------------------------------------------
# TMY3 writing
# ---------------------------------------------------------------------------

const TMY3_COLUMNS = [
    "Date (MM/DD/YYYY)",
    "Time (HH:MM)",
    "ETR (W/m^2)",
    "ETRN (W/m^2)",
    "GHI (W/m^2)",
    "GHI source",
    "GHI uncert (%)",
    "DNI (W/m^2)",
    "DNI source",
    "DNI uncert (%)",
    "DHI (W/m^2)",
    "DHI source",
    "DHI uncert (%)",
    "Pressure (mbar)",
    "Pressure source",
    "Pressure uncert (%)",
    "Dry-bulb (C)",
    "Dry-bulb source",
    "Dry-bulb uncert (%)",
    "RHum (%)",
    "RHum source",
    "RHum uncert (%)",
    "Wdir (degrees)",
    "Wdir source",
    "Wdir uncert (%)",
    "Wspd (m/s)",
    "Wspd source",
    "Wspd uncert (%)",
    "Pwat (cm)",
    "Pwat source",
    "Pwat uncert (%)",
    "Alb (unitless)",
    "Alb source",
    "Alb uncert (%)",
]

function write_tmy3(dir, name, stamps, tz_hours)
    path = joinpath(dir, name)
    open(path, "w") do io
        @printf(
            io,
            "%s,%s,%s,%.1f,%.3f,%.3f,%.1f\n",
            "062600",
            "De Bilt",
            "NLD",
            tz_hours,
            EPW_LAT,
            EPW_LON,
            EPW_ALT
        )
        println(io, join(TMY3_COLUMNS, ","))
        for s in stamps
            ghi, dni, dhi, μ = clear_sky(s, tz_hours)
            d, h, _ = epw_datetime_fields(s)
            fields = [
                @sprintf("%02d/%02d/%04d", month(d), day(d), year(d)),
                @sprintf("%02d:00", h),
                "0",
                "0",
                @sprintf("%.0f", ghi),
                "1",
                "8",
                @sprintf("%.0f", dni),
                "1",
                "9",
                @sprintf("%.0f", dhi),
                "1",
                "11",
                @sprintf("%.0f", 1013.25),
                "1",
                "1",   # mbar, not Pa
                @sprintf("%.1f", 12 + 9μ),
                "1",
                "7",
                @sprintf("%.0f", 70 - 20μ),
                "1",
                "8",
                "230",
                "1",
                "6",
                @sprintf("%.1f", 3.4 + μ),
                "1",
                "5",
                @sprintf("%.1f", 1.5),
                "1",
                "9",       # cm, not mm
                "0.200",
                "1",
                "12",
            ]
            println(io, join(fields, ","))
        end
    end
    return path
end

# ---------------------------------------------------------------------------
# The fixtures
# ---------------------------------------------------------------------------

"""
Write the cos(zenith) used to build a fixture, one value per record.

The closure and limit checks take cos(zenith) from the caller, so the tests need
the same values the data was constructed from. Recomputing them in the test would
duplicate the solar geometry and could drift from it.
"""
function write_cosz(dir, name, stamps, tz_hours)
    path = joinpath(dir, name)
    open(path, "w") do io
        println(io, "cosz")
        for s in stamps
            _, _, _, mu = clear_sky(s, tz_hours)
            @printf(io, "%.10f\n", mu)
        end
    end
    return path
end

function make_all(dir = HERE)
    written = String[]

    # 3 clean hourly days, UTC+1.
    push!(
        written,
        write_epw(dir, "minimal.epw", local_stamps(Date(2020, 6, 20), 3, 1), 1.0, 1),
    )

    # 15-minute records. Catches the Wh/m2 -> W/m2 scaling.
    push!(
        written,
        write_epw(dir, "subhourly.epw", local_stamps(Date(2020, 6, 20), 1, 4), 1.0, 4),
    )

    # Spring forward: the local clock jumps 02:00 -> 03:00, so the file is written
    # in UTC+1 before the transition and UTC+2 after. Parsed at the file's single
    # declared offset the UTC stamps stay uniform, which is the point.
    push!(
        written,
        write_epw(dir, "dst_spring.epw", local_stamps(Date(2020, 3, 28), 3, 1), 1.0, 1),
    )

    # Fall back.
    push!(
        written,
        write_epw(dir, "dst_autumn.epw", local_stamps(Date(2020, 10, 24), 3, 1), 1.0, 1),
    )

    # Four consecutive hours removed from the middle of day 2.
    full = local_stamps(Date(2020, 6, 20), 3, 1)
    holed = vcat(full[1:30], full[35:end])
    push!(written, write_epw(dir, "gap.epw", holed, 1.0, 1))

    # Closure: consistent by construction.
    push!(
        written,
        write_epw(dir, "closure_good.epw", local_stamps(Date(2020, 6, 20), 2, 1), 1.0, 1),
    )

    # Closure: DHI inflated 30% at these 1-based record indices, chosen to be
    # daylight hours on both days. test-qc-closure.jl asserts exactly this set.
    bad_indices = [12, 13, 14, 36, 37, 38]
    push!(
        written,
        write_epw(
            dir,
            "closure_bad.epw",
            local_stamps(Date(2020, 6, 20), 2, 1),
            1.0,
            1;
            corrupt = (i, ghi, dni, dhi, μ) ->
                i in bad_indices ? (ghi, dni, 1.3 * dhi) : (ghi, dni, dhi),
        ),
    )

    # Deliberately broken: the fall-back hour recorded twice, as happens when a
    # DST-aware local series is written out without resolving the ambiguity. Real
    # EPW files are in local standard time and never contain this. It exists so
    # the :duplicate_ts check has something to fire on.
    autumn = local_stamps(Date(2020, 10, 24), 3, 1)
    dup_at = findfirst(==(DateTime(2020, 10, 25, 3)), autumn)
    dup_at === nothing && error("fall-back hour not present in the autumn stamps")
    push!(
        written,
        write_epw(
            dir,
            "dst_duplicate.epw",
            vcat(autumn[1:dup_at], autumn[dup_at:end]),
            1.0,
            1,
        ),
    )

    push!(
        written,
        write_cosz(dir, "closure_cosz.csv", local_stamps(Date(2020, 6, 20), 2, 1), 1.0),
    )

    push!(
        written,
        write_tmy3(dir, "minimal_tmy3.csv", local_stamps(Date(2020, 6, 20), 3, 1), -5.0),
    )

    return written
end

if abspath(PROGRAM_FILE) == @__FILE__
    for p in make_all()
        @info "wrote" path = relpath(p)
    end
end
